# Generated by Django 2.1.5 on 2019-02-03 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janeway', '0002_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janeway_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('supertype', models.CharField(choices=[('production', 'Production'), ('graphics', 'Graphics'), ('music', 'Music')], max_length=20)),
                ('author_names', models.ManyToManyField(related_name='authored_releases', to='janeway.Name')),
            ],
        ),
    ]
