# Generated by Django 2.1.5 on 2019-07-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janeway', '0005_credit'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='country_code',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='author',
            name='janeway_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='janeway_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='name',
            name='janeway_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
        migrations.AlterField(
            model_name='release',
            name='janeway_id',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
