# Generated by Django 2.1.5 on 2019-07-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janeway', '0006_add_country_code_and_janeway_id_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
