# Generated by Django 2.1.5 on 2019-07-17 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('janeway', '0007_author_is_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janeway_id', models.IntegerField(db_index=True, unique=True)),
                ('url', models.URLField(max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='download_links', to='janeway.Release')),
            ],
        ),
    ]
