# Generated by Django 2.1.5 on 2019-07-18 08:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('janeway', '0009_packcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundtrackLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soundtrack_links', to='janeway.Release')),
                ('soundtrack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appearances_as_soundtrack', to='janeway.Release')),
            ],
        ),
    ]
