# Generated by Django 2.1.5 on 2019-07-18 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janeway', '0010_soundtracklink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='janeway_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
