# Generated by Django 2.1.5 on 2019-07-18 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janeway', '0011_make_credit_janeway_id_non_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='platform',
            field=models.CharField(blank=True, choices=[('ocs', 'Amiga OCS/ECS'), ('aga', 'Amiga AGA'), ('ppc', 'Amiga PPC/RTG')], max_length=20),
        ),
    ]
