# Generated by Django 2.1.5 on 2019-07-19 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janeway', '0012_release_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='release_date_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='release',
            name='release_date_precision',
            field=models.CharField(blank=True, choices=[('d', 'Day'), ('m', 'Month'), ('y', 'Year')], max_length=1),
        ),
    ]
