# Generated by Django 2.1.5 on 2019-11-03 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('janeway', '0014_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='screenshot',
            name='suffix',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
